### ISSUE TITLE
LILA (Eval Task)

### ISSUE THREAD

**Issue by haileyschoelkopf** [zhangir-azerbayev/math-lm#3]

**Comment by wellecks** [comment]
I'll take this one

**Comment by wellecks** [comment]
First I'll need to update the format of the huggingface dataset

**Comment by wellecks** [comment]
Ok the new version of the huggingface dataset is done! https://huggingface.co/datasets/allenai/lila

Using this, we will be able to evaluate on individual datasets (e.g. `datasets.load_dataset("allenai/lila", "addsub")`) or the full "multitask" splits that we used in the paper (`datasets.load_dataset("allenai/lila", "iid"`).

**Comment by wellecks** [comment]
development is here: https://github.com/wellecks/lm-evaluation-harness

The initial version is implemented and I successfully tried `addsub` on gpt-neo-1.3B and gpt-j. There is still some answer-parsing logic to add in for some of the datasets

**Comment by wellecks** [comment]
I've updated the implementation and tested four of the tasks (SVAMP, addsub, multiarith, GSM8k):

| Model  | SVAMP | addsub | multiarith | GSM8k | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| GPT Neo 1.3B  |  0.1605 | 0.5046 | 0.2299 | 0.0137 |
| GPT Neo 2.7B  | 0.1371 | 0.5046 | 0.2759 | 0.0206 |
| GPT-J 6B  | 0.2375 | 0.6606 | 0.3966 | 0.0429 |

I'm running the full IID evaluation (which takes awhile since it has ~30k test examples). If it looks good then I think this is ready to go.

**Comment by wellecks** [comment]
cc @zhangir-azerbayev @haileyschoelkopf

**Comment by haileyschoelkopf** [comment]
This looks great, thanks so much for contributing it!! Can review after tomorrow's meeting :)

**Comment by wellecks** [comment]
merged this into https://github.com/wellecks/lm-evaluation-harness

@haileyschoelkopf I can make a separate PR for the official eleuther repo if there's interest (the version in my fork has a couple minor differences, e.g. saving outputs, that could be removed for the PR)
